name: Build and publish release

on:
  push:
    branches:
      - master
      - feature/build-publish-binaries

jobs:
  checks:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: run
      uses: cedrickring/golang-action@1.4.1